mkdocs.yml: add links of social media
shellhub-io/shellhub-io.github.io pull request #2
Opened 2020-01-28 19:32 UTC by Domarys

2020-01-28 19:48 UTC, otavio requested changes

2020-01-28 19:48 UTC, otavio commented on mkdocs.yml
> +copyright: 'Copyright &copy; 2019 O.S.System'
The company name is `O.S. Systems`

2020-01-28 20:02 UTC, gustavosbarreto commented on mkdocs.yml
> +copyright: 'Copyright &copy; 2019 O.S.System'
2020

2020-01-28 20:09 UTC, Domarys commented on mkdocs.yml
> +copyright: 'Copyright &copy; 2019 O.S.System'
fixed

2020-01-28 20:13 UTC, otavio commented on mkdocs.yml
> +copyright: 'Copyright &copy; 2019 O.S. System'
@Domarys the other minor thing is the year. We are past 2019 already ;-)

2020-01-29 14:55 UTC, otavio requested changes

2020-01-29 14:55 UTC, otavio commented on mkdocs.yml
> +
There is no newline at end of file. Likely previous line has a spurious space or something like that.

2020-01-29 14:55 UTC, otavio commented on mkdocs.yml
> +
This commit should be squashed on previous one.

2020-01-30 13:35 UTC, merged