docs: add warning label to SSHID
shellhub-io/shellhub-io.github.io pull request #32
Opened 2022-06-28 21:03 UTC by gessecarneiro

2022-06-28 21:07 UTC, otavio requested changes

2022-06-28 21:07 UTC, otavio commented on docs/getting-started/connecting-device.md
> +    `<SSHID>` is composed of `<device name>@<server address>`. The server address has an additional @, characteristic of shellhub syntax.
ShellHub

2022-06-29 13:24 UTC, gessecarneiro commented on docs/getting-started/connecting-device.md
> +    `<SSHID>` is composed of `<device name>@<server address>`. The server address has an additional @, characteristic of shellhub syntax.
Solved.

2022-06-29 13:31 UTC, otavio requested changes

2022-06-29 13:31 UTC, otavio commented on docs/getting-started/connecting-device.md
> +    `<SSHID>` is composed of `<device name>@<server address>`. The server address has an additional @, characteristic of ShellHub syntax.
```suggestion
!!! warning ""
    `<SSHID>` is composed of `<device name>@<server address>`. The server address has an additional @, characteristic of ShellHub syntax.

```

2022-06-29 13:50 UTC, otavio approved these changes

2022-06-29 16:02 UTC, merged